package com.github.cetoprca.dtogenerator.annotation;

import java.lang.annotation.ElementType;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;

/**
 * Marks a class to generate DTOs upon compile time.
 * Classes marked with this annotation will generate a full DTO with all the class's fields, except those marked with {@Secret}
 * More DTOs can be generated by marking fields with {@AppearsInDTO}
 */
@Retention(RetentionPolicy.SOURCE)
@Target(ElementType.TYPE)
public @interface GenerateDTO {
}
